#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Android_CityWeather.Resource", IsApplication=true)]

namespace Android_CityWeather
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int theme_holo_light_background = 2131034112;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f07001b
			public const int checkBox1 = 2131165211;
			
			// aapt resource value: 0x7f07001c
			public const int checkBox2 = 2131165212;
			
			// aapt resource value: 0x7f07001d
			public const int checkBox3 = 2131165213;
			
			// aapt resource value: 0x7f070006
			public const int city = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int citySect = 2131165189;
			
			// aapt resource value: 0x7f070014
			public const int condSection = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int condlabel = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int condtext = 2131165206;
			
			// aapt resource value: 0x7f070008
			public const int country = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int countrySect = 2131165191;
			
			// aapt resource value: 0x7f07000a
			public const int find = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int getSection = 2131165193;
			
			// aapt resource value: 0x7f070011
			public const int humSection = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int humlabel = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int humtext = 2131165203;
			
			// aapt resource value: 0x7f07001e
			public const int image = 2131165214;
			
			// aapt resource value: 0x7f070002
			public const int linearLayout1 = 2131165186;
			
			// aapt resource value: 0x7f070017
			public const int linearLayout2 = 2131165207;
			
			// aapt resource value: 0x7f07001a
			public const int linearLayout3 = 2131165210;
			
			// aapt resource value: 0x7f070000
			public const int mainLayout = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int space1 = 2131165185;
			
			// aapt resource value: 0x7f070018
			public const int space2 = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int space4 = 2131165209;
			
			// aapt resource value: 0x7f07000e
			public const int tempSection = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int templabel = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int temptext = 2131165200;
			
			// aapt resource value: 0x7f070003
			public const int textView1 = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int textView2 = 2131165188;
			
			// aapt resource value: 0x7f07000b
			public const int timeSection = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int timelabel = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int timetext = 2131165197;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_Custom = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
